Added some test cases
IMax153/docs-ts pull request #1
Opened 2020-11-17 20:14 UTC by gillchristian

2020-11-17 20:16 UTC, gillchristian commented on test/Parser.ts
> +      it('should not include variables declared in a for loops', () => {
```suggestion
      it('should not include variables declared in for loops', () => {
```

2020-11-18 21:24 UTC, IMax153 requested changes

2020-11-18 21:24 UTC, IMax153 commented on test/utils.ts
> +export const assertLeft = <E, A = unknown>(either: E.Either<E, A>, onLeft: (e: E) => void) =>
We may want to consider utilizing these helpers throughout the test suite to help clean up the syntax

2020-11-18 21:26 UTC, IMax153 commented
@gillchristian - Thank you so much for your work on this so far!

> I tried to add some test cases to cover those missing branches/lines in the coverage but I did not find the way.

I really do think it is actually impossible to trigger those branches of execution, but the code was written as such to allow the type guards to correctly infer the types from `ts-morph`. For the `getFunctionDeclarations` and `parseConstants` functions, I am going to try to rewrite the logic to see if I can avoid having separate branches of execution and instead just return a `boolean`.

> Any suggestions on the approach I took? 

I think for the most part the approach looks good to me. I noted some comments above that you could consider.
 
> UPDATE 2: when adding test cases to Core I found out non-overwrite files were getting overwritten if the contents were different.

This behavior is actually what I intended when writing that bit of code. Consider the following scenario:
1. Run `docs-ts` without a config file, which causes the `searchEnabled` property to be set to `true` by default.
2. Generates a `_config.yml` with `search_enabled: true`
3. Create a `docs-ts.json` with `searchEnabled` set to `false`
4. Run `docs-ts` again

In the scenario above, running `docs-ts` a second time will not update the `_config.yml` as it should. For the `_config.yml` specifically, we need to first check whether or not the content has changed to determine if the file should be **forcibly** overwritten. However, we could improve the efficiency of this validation step by first checking if the file name contains `_config.yml`, but I favor the former implementation.

2020-11-18 21:26 UTC, gillchristian commented on test/utils.ts
> +export const assertLeft = <E, A = unknown>(either: E.Either<E, A>, onLeft: (e: E) => void) =>
Sure thing, I can convert all the assertions on left/right to this. Wanted to check first if it made sense to you

2020-11-18 21:37 UTC, gillchristian commented
> I really do think it is actually impossible to trigger those branches of execution

Yeah, I think as well. I was going to suggest to ignore the coverage then. But if you find the way to re-write it in a way to avoid this as all that would be optimal.

> This behavior is actually what I intended when writing that bit of code

I see. It makes. There's a problem tho, what if the user added changes on top that they'd want to keep? Maybe we can convert the yml file to JSON and add the config but keep the rest? :thinking: 

I think think this is special overwrite behavior is only particular to the `docs/_config.yml`. Because it can be edited both by users and by `docs-ts`.

`docs/index.md` might be overwritten by the user, since it's the index of the docs page. Should only be generated if missing.

`docs/modules/index.md` should actually be overwritten now that I think about because it's the ToC for the modules, users should not be editing manually.

2020-11-18 21:52 UTC, IMax153 commented
>There's a problem tho, what if the user added changes on top that they'd want to keep? 
 
Hmmm, good point. A given user would have any custom configuration that they provide after docs generation overwritten on subsequent iterations. Instead of the implementation that I went with, we could use a regular expression to only modify the `search_enabled` and `remote_theme` properties of the `_config.yml` if the file already exists? I will experiment a bit with this and get back to you.

> `docs/index.md` might be overwritten by the user, since it's the index of the docs page. Should only be generated if missing.

This is fair, so maybe it makes the most sense to only examine the `_config.yml` for changes at this step in the algorithm then.

2020-11-21 21:46 UTC, gillchristian commented
I rolled back the overwrite stuff and those tests. We can merge this and I'll work on other tests on the meantime.

2020-11-22 00:01 UTC, gillchristian commented on test/Core.ts
> +    { ...fs },
You are right.

Still needs to be in a closure and cannot use `R.empty` as the initial case because it gets mutated.

2020-11-22 14:54 UTC, IMax153 commented on test/Core.ts
> +    { ...fs },
> Still needs to be in a closure 

I don't believe this is true. `reduceWithIndex` returns a function that accepts a FileSystemState. The closure should be unnecessary.

> cannot use `R.empty` as the initial case because it gets mutated

You can fix the mutability issue here by changing the implementation of the reduction 

```ts
const prefixWithCwd: Endomorphism<FileSystemState> = R.reduceWithIndex<
  string, 
  string, 
  FileSystemState
>(R.empty, (key, acc, content) => ({
  ...acc,
  [path.join(process.cwd(), key)]: content
}))
```

2020-11-22 14:57 UTC, IMax153 commented on test/Core.ts
> +// TODO: use WritterT ?
I agree. I haven't had time to work on the PR as of late, but should have some time early next week. I can take a look at using the `Writer` monad here to make things a bit cleaner too.

2020-11-22 14:57 UTC, IMax153 commented on test/Core.ts
> +          assert.equal(error.startsWith('Unable to read package.json'), true)
Would you mind changing these to `assert.strictEqual` ? `assert.equal` is deprecated.

2020-11-22 15:49 UTC, gillchristian commented on test/Core.ts
> +// TODO: use WritterT ?
I didn't look into it, wanted to get something working first.

Would it be possible to implement it in a way that the `Capabilities` type supports it?

2020-11-22 15:53 UTC, gillchristian commented on test/Core.ts
> +          assert.equal(error.startsWith('Unable to read package.json'), true)
Good catch!

2020-11-23 18:20 UTC, IMax153 commented
@gillchristian - I just pushed some changes to the `Parser` module and added a test for the `getConstructorDeclarationSignature` function that gives us 100% test coverage of the `Parser` module.

I am going to take a look at using `Writer` for the `Capabilities` in the `Core` test suite.

Could you take a look at the requested change that I unresolved above and let me know your thoughts?

2020-11-23 19:56 UTC, IMax153 commented
After looking at this for a while, I don't think there is a simple way to implement the `Core` tests with `Writer`. I would be fine with leaving the implementation as is for now.

I am going to move on and work on the `enforceSince` configuration option.

2020-11-23 20:54 UTC, IMax153 commented
Okay, the most recent commits add in an `enforceVersion` configuration option which defaults to `true`. Now we just need to get your changes merged in and we should be good to merge this branch into the main repo.

Just ping me once your ready for another review! Thanks again for all your help on this!

2020-12-03 19:12 UTC, gillchristian commented on test/Core.ts
> +    { ...fs },
You were right, it was about the mutability in the implementation. Fixed

2020-12-03 19:12 UTC, gillchristian commented
@IMax153 pushed the fix to the mutability case. We can merge this I think. I can add more tests on a separate PR

2020-12-04 23:44 UTC, IMax153 approved these changes

2020-12-04 23:44 UTC, merged

2020-12-04 23:45 UTC, IMax153 commented
@gillchristian - thank you very much for all your help on this 👍. Merged. 

I will work on the issue regarding overwriting the `_config.yml` and then we can take this discussion back to the main repo.

2020-12-05 12:48 UTC, gillchristian commented
Sounds good. In the mean time, I'll see if I can write later tests for code that don't relay on checking the `_config.yml`.

2020-12-12 02:28 UTC, IMax153 commented
@gillchristian - I just added the regex logic for only modifying the portions of the `_config.yml` that are affected by the settings.

I would like to get us to 100% test coverage before we bring this back to the main repository. Were you able to progress the `Core` tests at all? I can help if not.

2020-12-12 07:29 UTC, gillchristian commented
I didn't, I was planning to do it next week. But of course you can take that up. I'll add tests to any other thing that is needed.